name: CI_UTESTS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run Tests and Coverage
        run: pnpm test
